server:
  port: 8888
spring:
  datasource:
    name: springdata
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: uWXf87plmQGz8zMM
    url: jdbc:mysql://172.18.1.104:53301/lolaage_egc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 50
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 50
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
