server:
  port: 8010
spring:
  application:
    name: mango-config
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}	# 注册到consul的服务名称
    config:
      server:
        git:
          uri: https://github.com/AVAL-NIX/springconfig.git #最后不需要带/，否则会出现：No custom http config found for URL: XXX）
          searchPaths: repo
          username:
          passowrd:
        default-label: main
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    bus-refresh:
      enabled: true
    health:
      show-details: ALWAYS
#
#  spring.cloud.config.server.git.uri：配置git仓库地址
#  spring.cloud.config.server.git.searchPaths：配置仓库路径
#  spring.cloud.config.default-label：配置仓库的分支
#  spring.cloud.config.server.git.username：访问git仓库的用户名
#  spring.cloud.config.server.git.password：访问git仓库的用户密码
#  如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写，本例子是公开仓库，放心使用。

